--- Dockerfile.orig
+++ Dockerfile.aarch64
@@ -1,6 +1,7 @@
 # Copyright (c) Jupyter Development Team.
 # Distributed under the terms of the Modified BSD License.
-ARG BASE_CONTAINER=jupyter/datascience-notebook
+ARG OWNER
+ARG BASE_CONTAINER=$OWNER/datascience-notebook
 FROM $BASE_CONTAINER
 
 LABEL maintainer="Yuuta Sakurai <sakurai@andrew.ac.jp>"
