--- Dockerfile	2021-03-11 16:38:08.402779087 +0000
+++ Dockerfile.aarch64	2021-03-11 16:37:50.154892845 +0000
@@ -1,6 +1,7 @@
 # Copyright (c) Jupyter Development Team.
 # Distributed under the terms of the Modified BSD License.
-ARG BASE_CONTAINER=jupyter/scipy-notebook
+ARG OWNER
+ARG BASE_CONTAINER=$OWNER/scipy-notebook
 FROM $BASE_CONTAINER
 
 LABEL maintainer="Jupyter Project <jupyter@googlegroups.com>"
@@ -19,8 +20,10 @@
 # (ARGS are in lower case to distinguish them from ENV)
 # Check https://julialang.org/downloads/
 ARG julia_version="1.5.3"
+ARG arch_short="aarch64"
+ARG arch="aarch64"
 # SHA256 checksum
-ARG julia_checksum="f190c938dd6fed97021953240523c9db448ec0a6760b574afd4e9924ab5615f1"
+ARG julia_checksum="1e8445eae896d347200b819b7a41778597ae15c314d9df080172eb868a42b628"
 
 # R pre-requisites
 RUN apt-get update && \
@@ -34,16 +37,18 @@
 # install Julia packages in /opt/julia instead of $HOME
 ENV JULIA_DEPOT_PATH=/opt/julia \
     JULIA_PKGDIR=/opt/julia \
-    JULIA_VERSION="${julia_version}"
+    JULIA_VERSION="${julia_version}" \
+    ARCH_SHORT="${arch_short}" \
+    ARCH="${arch}"
 
 WORKDIR /tmp
 
 # hadolint ignore=SC2046
 RUN mkdir "/opt/julia-${JULIA_VERSION}" && \
-    wget -q https://julialang-s3.julialang.org/bin/linux/x64/$(echo "${JULIA_VERSION}" | cut -d. -f 1,2)"/julia-${JULIA_VERSION}-linux-x86_64.tar.gz" && \
-    echo "${julia_checksum} *julia-${JULIA_VERSION}-linux-x86_64.tar.gz" | sha256sum -c - && \
-    tar xzf "julia-${JULIA_VERSION}-linux-x86_64.tar.gz" -C "/opt/julia-${JULIA_VERSION}" --strip-components=1 && \
-    rm "/tmp/julia-${JULIA_VERSION}-linux-x86_64.tar.gz"
+    wget -q https://julialang-s3.julialang.org/bin/linux/${ARCH_SHORT}/$(echo "${JULIA_VERSION}" | cut -d. -f 1,2)"/julia-${JULIA_VERSION}-linux-${ARCH}.tar.gz" && \
+    echo "${julia_checksum} *julia-${JULIA_VERSION}-linux-${ARCH}.tar.gz" | sha256sum -c - && \
+    tar xzf "julia-${JULIA_VERSION}-linux-${ARCH}.tar.gz" -C "/opt/julia-${JULIA_VERSION}" --strip-components=1 && \
+    rm "/tmp/julia-${JULIA_VERSION}-linux-${ARCH}.tar.gz"
 RUN ln -fs /opt/julia-*/bin/julia /usr/local/bin/julia
 
 # Show Julia where conda libraries are \
@@ -57,24 +62,24 @@
 USER $NB_UID
 
 # R packages including IRKernel which gets installed globally.
-RUN conda install --quiet --yes \
-    'r-base=4.0.3'  \
-    'r-caret=6.0*' \
-    'r-crayon=1.4*' \
-    'r-devtools=2.3*' \
-    'r-forecast=8.13*' \ 
-    'r-hexbin=1.28*' \
-    'r-htmltools=0.5*' \
-    'r-htmlwidgets=1.5*' \ 
-    'r-irkernel=1.1*' \
-    'r-nycflights13=1.0*' \
-    'r-randomforest=4.6*' \
-    'r-rcurl=1.98*' \
-    'r-rmarkdown=2.7*' \
-    'r-rsqlite=2.2*' \
-    'r-shiny=1.6*' \
-    'r-tidyverse=1.3*' \
-    'rpy2=3.4*' && \
+RUN mamba install --quiet --yes \
+    'r-base'  \
+    'r-caret' \
+    'r-crayon' \
+    'r-devtools' \
+    'r-forecast' \ 
+    'r-hexbin' \
+    'r-htmltools' \
+    'r-htmlwidgets' \ 
+    'r-irkernel' \
+    'r-nycflights13' \
+    'r-randomforest' \
+    'r-rcurl' \
+    'r-rmarkdown' \
+    'r-rsqlite' \
+    'r-shiny' \
+    'r-tidyverse=1.2.1' \
+    'rpy2' && \
     conda clean --all -f -y && \
     fix-permissions "${CONDA_DIR}" && \
     fix-permissions "/home/${NB_USER}"
