--- Dockerfile	2021-03-11 05:27:26.024722269 +0000
+++ Dockerfile.aarch64	2021-03-11 05:26:39.112795121 +0000
@@ -1,6 +1,7 @@
 # Copyright (c) Jupyter Development Team.
 # Distributed under the terms of the Modified BSD License.
-ARG BASE_CONTAINER=jupyter/base-notebook
+ARG OWNER
+ARG BASE_CONTAINER=$OWNER/base-notebook
 FROM $BASE_CONTAINER
 
 LABEL maintainer="Jupyter Project <jupyter@googlegroups.com>"
