--- Dockerfile	2021-03-11 05:27:26.020722274 +0000
+++ Dockerfile.aarch64	2021-03-11 05:26:39.108795129 +0000
@@ -2,7 +2,8 @@
 # Distributed under the terms of the Modified BSD License.
 
 # https://hub.docker.com/r/jupyter/base-notebook/tags
-ARG BASE_CONTAINER=jupyter/base-notebook:aec555e49be6
+ARG OWNER
+ARG BASE_CONTAINER=$OWNER/base-notebook
 FROM $BASE_CONTAINER
 
 LABEL maintainer="Jupyter Project <jupyter@googlegroups.com>"
