--- Dockerfile.orig
+++ Dockerfile.aarch64
@@ -21,7 +21,7 @@
 USER $NB_UID
 
 # Install Python 3 packages
-RUN ${CONDA_INSTALL_CMD} -c anaconda install --quiet --yes \
+RUN ${CONDA_INSTALL_CMD} install --quiet --yes \
     'beautifulsoup4=4.9.*' \
     'conda-forge::blas=*=openblas' \
     'bokeh=2.2.*' \
@@ -37,7 +37,7 @@
     'numba=0.52.*' \
     'numexpr=2.7.*' \
     'pandas=1.2.*' \
-    'pandas-datareader' \
+    'pandas-datareader=0.9.*' \
     'patsy=0.5.*' \
     'protobuf=3.15.*' \
     'pytables=3.6.*' \
