--- Dockerfile
+++ Dockerfile.aarch64
@@ -1,10 +1,16 @@
 # Copyright (c) Jupyter Development Team.
 # Distributed under the terms of the Modified BSD License.
-ARG BASE_CONTAINER=jupyter/minimal-notebook
+ARG OWNER
+ARG BASE_CONTAINER=$OWNER/minimal-notebook
 FROM $BASE_CONTAINER
 
 LABEL maintainer="Jupyter Project <jupyter@googlegroups.com>"
 
+# Default Package Manager command
+#ARG conda_install_cmd="conda"
+ARG conda_install_cmd="mamba"
+ENV CONDA_INSTALL_CMD="${conda_install_cmd}"
+
 USER root
 
 # ffmpeg for matplotlib anim & dvipng+cm-super for latex labels
@@ -15,7 +21,7 @@
 USER $NB_UID
 
 # Install Python 3 packages
-RUN conda install --quiet --yes \
+RUN ${CONDA_INSTALL_CMD} install --quiet --yes \
     'beautifulsoup4=4.9.*' \
     'conda-forge::blas=*=openblas' \
     'bokeh=2.2.*' \
@@ -31,6 +37,7 @@
     'numba=0.52.*' \
     'numexpr=2.7.*' \
     'pandas=1.2.*' \
+    'pandas-datareader=0.9.*' \
     'patsy=0.5.*' \
     'protobuf=3.15.*' \
     'pytables=3.6.*' \
